CREATE TABLE [Universal].[User]
(
	[UserId] UNIQUEIDENTIFIER NOT NULL PRIMARY KEY, 
	[FirstName] VARCHAR(50) NULL, 
	[LastName] VARCHAR(50) NULL, 
	[Email] VARCHAR(150) NULL,
	[CreatedOn] DATETIMEOFFSET NOT NULL,
	[LastModifiedOn] DATETIMEOFFSET NOT NULL,
	[SearchTerms] VARCHAR(150) NULL
)
